/**
 * LanPlay Setup — homebrew NRO configurator for switch-lan-play.
 *
 * Appears in Atmosphere hbmenu as "LanPlay Setup".
 *
 * What it does
 * ============
 * 1. Read the current relay server address from the config file (if any).
 * 2. Open the Switch on-screen keyboard pre-filled with the current address.
 * 3. Write the updated address back to the config file.
 * 4. Show a confirmation screen and exit.
 *
 * The player ONLY has to enter the relay server address — nothing else.
 * The IP is auto-generated by the sysmodule; no network manual config needed.
 *
 * Config file location
 * ====================
 *   sdmc:/config/lan-play/config.ini
 *
 * The file is created automatically if it does not exist.
 *
 * Build with devkitPro + libnx:
 *   cd hbapp && make
 * Copy lanplay-setup.nro to sdmc:/switch/lanplay-setup/lanplay-setup.nro
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <sys/stat.h>
#include <switch.h>

/* -------------------------------------------------------------------------
 * Config constants (must match sysmodule/source/config.h)
 * ---------------------------------------------------------------------- */
#define CONFIG_DIR  "sdmc:/config/lan-play"
#define CONFIG_PATH "sdmc:/config/lan-play/config.ini"
#define STR_MAX     256

/* -------------------------------------------------------------------------
 * Timing constant
 * ---------------------------------------------------------------------- */
#define SLEEP_1500MS     1500000000LL /* 1.5 seconds in nanoseconds */

/* -------------------------------------------------------------------------
 * Config file buffer sizes (must be ≥ sysmodule config.cpp values)
 * ---------------------------------------------------------------------- */
#define MAX_CONFIG_LINES 64
#define MAX_LINE_LEN     512
static PrintConsole g_console;

static void con_clear(void)
{
    consoleClear();
}

static void con_print(const char *fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vprintf(fmt, ap);
    va_end(ap);
}

/* -------------------------------------------------------------------------
 * INI helpers — minimal (same logic as sysmodule config.cpp)
 * ---------------------------------------------------------------------- */
static void trim(char *s)
{
    char *p = s;
    while (*p == ' ' || *p == '\t') p++;
    if (p != s) memmove(s, p, strlen(p) + 1);
    size_t len = strlen(s);
    while (len > 0 && (s[len-1] == ' '  || s[len-1] == '\t' ||
                       s[len-1] == '\r' || s[len-1] == '\n'))
        s[--len] = '\0';
}

/**
 * read_relay — scan config.ini for the relay_addr key.
 * Returns 0 and fills buf on success, -1 if not found.
 */
static int read_relay(char *buf, size_t bufsz)
{
    buf[0] = '\0';
    FILE *f = fopen(CONFIG_PATH, "r");
    if (!f) return -1;

    char line[512];
    while (fgets(line, sizeof(line), f)) {
        trim(line);
        if (line[0] == '\0' || line[0] == ';' ||
            line[0] == '#'  || line[0] == '[') continue;
        char *eq = strchr(line, '=');
        if (!eq) continue;
        *eq = '\0';
        char *key = line, *val = eq + 1;
        trim(key); trim(val);
        if (strcmp(key, "relay_addr") == 0) {
            strncpy(buf, val, bufsz - 1);
            buf[bufsz - 1] = '\0';
            fclose(f);
            return 0;
        }
    }
    fclose(f);
    return -1;
}

/**
 * save_relay — update or insert relay_addr in config.ini.
 * Preserves all other lines (auth username/password, comments).
 */
static int save_relay(const char *relay_addr)
{
    mkdir(CONFIG_DIR, 0777);

    char  lines[MAX_CONFIG_LINES][MAX_LINE_LEN];
    int   nlines = 0;
    bool  found  = false;

    FILE *r = fopen(CONFIG_PATH, "r");
    if (r) {
        while (nlines < MAX_CONFIG_LINES - 1 &&
               fgets(lines[nlines], MAX_LINE_LEN, r))
            nlines++;
        fclose(r);
    }

    for (int i = 0; i < nlines; i++) {
        char tmp[MAX_LINE_LEN];
        strncpy(tmp, lines[i], MAX_LINE_LEN - 1);
        tmp[MAX_LINE_LEN - 1] = '\0';
        trim(tmp);
        if (strncmp(tmp, "relay_addr", 10) == 0 && strchr(tmp, '=')) {
            snprintf(lines[i], MAX_LINE_LEN, "relay_addr = %s\n", relay_addr);
            found = true;
            break;
        }
    }

    if (!found) {
        if (nlines == 0) {
            snprintf(lines[nlines++], MAX_LINE_LEN, "; switch-lan-play configuration\n");
            snprintf(lines[nlines++], MAX_LINE_LEN, "[server]\n");
        }
        snprintf(lines[nlines++], MAX_LINE_LEN, "relay_addr = %s\n", relay_addr);
    }

    FILE *w = fopen(CONFIG_PATH, "w");
    if (!w) return -1;
    for (int i = 0; i < nlines; i++) fputs(lines[i], w);
    fclose(w);
    return 0;
}

/* -------------------------------------------------------------------------
 * On-screen keyboard wrapper
 * ---------------------------------------------------------------------- */
static bool ask_relay(const char *current, char *out, size_t outsz)
{
    SwkbdConfig kbd;
    swkbdConfigMakePresetDefault(&kbd);

    swkbdConfigSetHeaderText(&kbd,
        "LanPlay — Enter relay server address");
    swkbdConfigSetSubText(&kbd,
        "Format: host:port  (e.g. relay.example.com:11451)");
    swkbdConfigSetGuideText(&kbd,
        "relay.example.com:11451");
    swkbdConfigSetStringLenMax(&kbd, (uint32_t)(outsz - 1));
    swkbdConfigSetType(&kbd, SwkbdType_Normal);

    /* Pre-fill with the current value so the user only has to edit it */
    if (current[0] != '\0')
        swkbdConfigSetInitialText(&kbd, current);

    Result rc = swkbdShow(&kbd, out, outsz);
    swkbdClose(&kbd);

    if (R_FAILED(rc) || out[0] == '\0') return false;

    /* Strip leading/trailing whitespace */
    trim(out);
    return out[0] != '\0';
}

/* -------------------------------------------------------------------------
 * Main
 * ---------------------------------------------------------------------- */
int main(int argc, char *argv[])
{
    (void)argc; (void)argv;

    /* Init services */
    fsdevMountSdmc();
    consoleInit(NULL);

    /* ------------------------------------------------------------------ */
    /* Title screen                                                         */
    /* ------------------------------------------------------------------ */
    con_clear();
    con_print("\n\n");
    con_print("  ================================\n");
    con_print("       LanPlay Setup  v1.0\n");
    con_print("  ================================\n\n");

    char current[STR_MAX] = {0};
    if (read_relay(current, sizeof(current)) == 0) {
        con_print("  Current server: %s\n\n", current);
    } else {
        con_print("  No server configured yet.\n\n");
    }

    con_print("  Press A to set / update the server.\n");
    con_print("  Press B to cancel and exit.\n\n");

    /* Wait for A or B */
    bool proceed = false;
    PadState pad;
    padInitializeDefault(&pad);
    while (appletMainLoop()) {
        padUpdate(&pad);
        u64 kDown = padGetButtonsDown(&pad);
        if (kDown & HidNpadButton_A) { proceed = true;  break; }
        if (kDown & HidNpadButton_B) { proceed = false; break; }
        consoleUpdate(NULL);
    }

    if (!proceed) {
        con_print("\n  Cancelled.  Exiting...\n");
        consoleUpdate(NULL);
        svcSleepThread(SLEEP_1500MS);
        consoleExit(NULL);
        fsdevUnmountAll();
        return 0;
    }

    /* ------------------------------------------------------------------ */
    /* On-screen keyboard                                                   */
    /* ------------------------------------------------------------------ */
    char new_relay[STR_MAX] = {0};
    if (!ask_relay(current, new_relay, sizeof(new_relay))) {
        con_clear();
        con_print("\n\n  No address entered.  Exiting...\n");
        consoleUpdate(NULL);
        svcSleepThread(SLEEP_1500MS);
        consoleExit(NULL);
        fsdevUnmountAll();
        return 0;
    }

    /* ------------------------------------------------------------------ */
    /* Save & confirm                                                       */
    /* ------------------------------------------------------------------ */
    con_clear();
    con_print("\n\n");
    con_print("  ================================\n");
    con_print("       LanPlay Setup  v1.0\n");
    con_print("  ================================\n\n");

    if (save_relay(new_relay) == 0) {
        con_print("  [OK] Server saved:\n");
        con_print("       %s\n\n", new_relay);
        con_print("  Reboot the Switch to apply.\n\n");
        con_print("  (The sysmodule will auto-assign\n");
        con_print("   a unique IP — no manual network\n");
        con_print("   settings needed.)\n\n");
    } else {
        con_print("  [ERROR] Could not write config file.\n");
        con_print("  Make sure the SD card is writable.\n\n");
    }

    con_print("  Press any button to exit.\n");
    consoleUpdate(NULL);

    /* Wait for any button */
    PadState pad_exit;
    padInitializeDefault(&pad_exit);
    while (appletMainLoop()) {
        padUpdate(&pad_exit);
        if (padGetButtonsDown(&pad_exit)) break;
        consoleUpdate(NULL);
    }

    consoleExit(NULL);
    fsdevUnmountAll();
    return 0;
}
